name: Update CRAN@GH

on:
  workflow_dispatch:
  schedule:
    - cron:  '23 * * * *'

jobs:
  gh-update:
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/r-hub/cranatgh/cranatgh:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        CRANATGH_GITHUB_TOKEN: ${{ secrets.CRANATGH_GITHUB_TOKEN }}

    steps:
      - name: Update outdated packages
        run: |
          cranatgh::update_all_packages(max_failures = 1000)
        shell: Rscript {0}
